# Generated by Django 2.2 on 2019-12-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191213_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='iden',
            field=models.CharField(default='asdf', max_length=50),
            preserve_default=False,
        ),
    ]
