# Generated by Django 2.2 on 2020-01-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
