# Generated by Django 2.2 on 2020-01-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_item_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=70)),
                ('order_id', models.CharField(max_length=70)),
                ('gross_amount', models.CharField(max_length=70)),
                ('payment_type', models.CharField(max_length=70)),
                ('transaction_time', models.CharField(max_length=70)),
                ('transaction_status', models.CharField(max_length=70)),
                ('fraud_status', models.CharField(max_length=70)),
                ('masked_card', models.CharField(max_length=70)),
                ('status_code', models.CharField(max_length=70)),
                ('bank', models.CharField(max_length=70)),
                ('status_message', models.CharField(max_length=70)),
                ('approval_code', models.CharField(max_length=70)),
                ('channel_response_code', models.CharField(max_length=70)),
                ('channel_response_message', models.CharField(max_length=70)),
                ('currency', models.CharField(max_length=70)),
                ('card_type', models.CharField(max_length=70)),
            ],
        ),
    ]
