# Generated by Django 2.2 on 2020-01-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
